### ISSUE TITLE
Maximum iterations in solve() method using max_iter parameter

### ISSUE THREAD

**Issue by govind-menon110** [oemof/tespy#269] opened 2021-05-24 18:36 UTC
Hi @fwitte,
Is max_iter statically fixed at 50 and any value above 50 in `nw.solve(max_iter=num)` ignored if num > 50?

Regards,
Govind

**Comment by fwitte** [comment] 2021-05-24 20:33
Hi, it should not, see https://github.com/oemof/tespy/blob/2df2b6a4f239acf31dfbcc6ba30be13660609a70/src/tespy/networks/network.py#L1682. However, There is a termination criterion, if the iteration count is larger than 40 and no progress in residual value is found (some 10 lines below).

In general, 10 to 20 Newton iterations should always find the solution in a well determined model. Maybe you need to double-check the model specifications?

**Comment by fwitte** [comment] 2021-07-14 06:32
Hi @govind-menon110,
any news on this?
Best
Francesco

**Comment by govind-menon110** [comment] 2021-07-14 06:37
> Hi @govind-menon110,
> any news on this?
> Best
> Francesco

Hi @fwitte ,
I tried changing the parameters and the design case solved pretty quick. However an offdesign case with changed mass flow rates still cut off at 50 iterations though the maximum iterations were 100. Will update you again in a while. 

Regards,
Govind

**Comment by fwitte** [comment] 2021-07-14 06:41
Well, my guess is that there are some specifications regarding design/offdesign parameters, that do not work well/as intended. The algorithm should really be able to find the solution within less than 10 to 20 iterations. Good luck on finding the issue :).

**Comment by fwitte** [comment] 2022-10-02 08:56
@govind-menon110: I will close this for the time being, if you still need help please feel free to comment or open a discussion :)

**Closed** 2022-10-02 08:55 UTC
Labels: question
